export type Asset = { url: string; name: string; kind: 'photo' | 'drawing'; latitude?: number; longitude?: number; date?: string };
export type Entry = { id: string; city: string; region: string; date: string; title: string; note: string; kind: 'visit' | 'wish'; assets: Asset[]; latitude?: number; longitude?: number; demo?: boolean };
export const examples: Entry[] = [
 { id:'demo-sedona',city:'Sedona',region:'Arizona',date:'2025-04-18',title:'A little closer to the earth.',note:'Red dust on my shoes. The kind of quiet that makes you want to stay a little longer.\n\nWe took the long way back, stopped whenever the light changed, and forgot what time it was.\n\nA reminder to myself: leave room for the unplanned.',kind:'visit',latitude:34.8697,longitude:-111.761,assets:[{url:'/images/sedona.jpg',name:'The red rocks, just before sunset',kind:'photo'}],demo:true },
 { id:'demo-sf',city:'San Francisco',region:'California',date:'2025-02-08',title:'Following the fog.',note:'A whole day of walking with no particular destination. Coffee, steep streets, and the ocean at the end of it all.\n\nSome cities feel like a conversation you want to keep having.',kind:'visit',latitude:37.7749,longitude:-122.4194,assets:[{url:'/images/san-francisco.jpg',name:'A city in the clouds',kind:'photo'}],demo:true },
 { id:'demo-kyoto',city:'Kyoto',region:'Japan',date:'',title:'For a slower kind of morning.',note:'A little street, a sketchbook, and nowhere to rush. Saving this for the trip I keep dreaming about.',kind:'wish',assets:[{url:'/images/kyoto.jpg',name:'The image that started the daydream',kind:'photo'}],demo:true }
];
export const prettyDate = (date:string) => date ? new Date(date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}) : 'Someday';
export function nearby(lat:number, lon:number, entry:Entry) { if(entry.latitude == null || entry.longitude == null)return false; const r = Math.PI/180;const a=Math.sin((lat-entry.latitude)*r/2)**2+Math.cos(lat*r)*Math.cos(entry.latitude*r)*Math.sin((lon-entry.longitude)*r/2)**2;return 6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))<20; }

export function visitNumber(entry:Entry, entries:Entry[]){return entries.filter(e=>e.kind==='visit'&&e.city.trim().toLowerCase()===entry.city.trim().toLowerCase()&&e.region.trim().toLowerCase()===entry.region.trim().toLowerCase()).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id)).findIndex(e=>e.id===entry.id)+1;}
export function photoGroups(assets:Asset[]){const groups:Asset[][]=[];for(const asset of assets){if(asset.kind==='drawing')continue;const group=groups.find(g=>{const first=g[0];const sameDate=(asset.date||'')===(first.date||'');const hasGps=asset.latitude!=null&&asset.longitude!=null;const firstHasGps=first.latitude!=null&&first.longitude!=null;return sameDate&&hasGps===firstHasGps&&(!hasGps||nearby(asset.latitude!,asset.longitude!,{latitude:first.latitude,longitude:first.longitude} as Entry));});if(group)group.push(asset);else groups.push([asset]);}return groups;}
